services:
  db:
    image: mariadb:12.1.2-noble
    ports:
      - "3306:3306"
    env_file:
      - base.env
      - var.env 
      - dev.env
    environment:
      # Значения переопределяют значения из.env файла
      MARIADB_DATABASE: my_database
      MARIADB_PASSWORD: 123
      OTHER_ENVIRONMENT_VARIABLE: "some value"
  frontend:
    image: nginx:1.29.4-alpine3.23
    ports:
      - "8085:80"
  redis:
    image: redis:8.4.0-alpine3.22
    ports:
      - "6379:6379"
  kafka:
    image: apache/kafka:4.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

