services:
  db:
    image: mariadb:12.1.2-noble
    ports:
      # Проброс порта 3306 из контейнера MariaDB.
      - "3306:3306"
    env_file:
      # Переменные окружения считываются из файлов
      # в порядке перечисления файлов.
      - base.env
      - var.env 
      - dev.env
    environment:
      # Значения переопределяют значения из.env файла.
      MARIADB_DATABASE: my_database
      MARIADB_PASSWORD: 123
      OTHER_ENVIRONMENT_VARIABLE: "some value"
  frontend:
    image: nginx:1.29.4-alpine3.23
    ports:
      # Проброс порта 80 из контейнера Nginx
      # на порт 8085 хоста.
      - "8085:80"
    env_file:
      - path: ./other.env
      - required: false
  redis:
    image: redis:8.4.0-alpine3.22
    ports:
      # Проброс порта 6379 из контейнера Redis.
      - "6379:6379"
    env_file: redis.env
  kafka:
    image: apache/kafka:4.1.1
    ports:
      # Проброс портов 9092 и 9093 из контейнера Kafka.
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

