services:
  db:
    image: mariadb:12.1.2-noble
    ports:
      # Проброс порта 3306 из контейнера MariaDB.
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD_FILE : /run/secrets/db_root_password 
      MARIADB_DATABASE : my_database
      MARIADB_USER : my_user
      MARIADB_PASSWORD_FILE : /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
volumes:
  db_data:

secrets:
    db_password:
      file: db_password.txt
    db_root_password:
      environment: PASS

