services:
  db:
    image: mariadb:12.1.2-noble
    ports:
      # Проброс порта 3306 из контейнера MariaDB.
      - "3306:3306"
    env_file:
      - dev.env
    volumes:
      - db_data:/var/lib/mysql
  nginx:
    image: nginx:1.29.4-alpine3.23
    ports:
      # Проброс порта 80 из контейнера Nginx
      # на порт 8080 хоста.
      - "8080:80"
    volumes:
      - ./website:/usr/share/nginx/html
volumes:
  db_data:

