services:
  db:
    image: mariadb:12.1.2-noble
    ports:
      # Проброс порта 3306 из контейнера MariaDB.
      - "3306:3306"
  frontend:
    image: nginx:1.29.4-alpine3.23
    ports:
      # Проброс порта 80 из контейнера Nginx
      # на порт 8085 хоста.
      - "8085:80"
  redis:
    image: redis:8.4.0-alpine3.22
    ports:
      # Проброс порта 6379 из контейнера Redis.
      - "6379:6379"
  kafka:
    image: apache/kafka:4.1.1
    ports:
      # Проброс портов 9092 и 9093 из контейнера Kafka.
      - "9092:9092"
      - "9093:9093"
