services:
  db:
    image: mariadb:12.1.2-noble
    ports:
      # Проброс порта 3306 из контейнера MariaDB.
      - "3306:3306"
    env_file:
      # Переменные окружения считываются из файлов
      # в порядке перечисления файлов.
      - dev.env
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  backend1:
    image: nginx:1.29.4-alpine3.23
    ports:
      # Проброс порта 80 из контейнера Nginx
      # на порт 8085 хоста.
      - "8085:80"
    depends_on:
      - db
      - redis
      - kafka
  backend2:
    image: nginx:1.29.4-alpine3.23
    ports:
      # Проброс порта 80 из контейнера Nginx
      # на порт 8086 хоста.
      - "8086:80"
    depends_on:
      db:
        # Должен выполняться healthcheck.
        condition: service_healthy
        # Перезапускать backend2 при перезапуске db.
        restart: true
      redis:
        # Сервиса должен быть запущен.
        condition: service_started
        # Redis не обязателен.
        required: false
      kafka:
        # Сервис должен быть запущен.
        condition: service_started
      hello:
        # Сервис hello должен быть завершен успешно.
        condition: service_completed_successfully
  hello:
    image: hello-world:latest
  redis:
    image: redis:8.4.0-alpine3.22
    ports:
      # Проброс порта 6379 из контейнера Redis.
      - "6379:6379"
  kafka:
    image: apache/kafka:4.1.1
    ports:
      # Проброс портов 9092 и 9093 из контейнера Kafka.
      - "9092:9092"
      - "9093:9093"


