services:
  db:
    image: mariadb:12.1.2-noble
    ports:
      # Проброс порта 3306 из контейнера MariaDB.
      - "3306:3306"
    env_file:
      - dev.env
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:

